const test=require('node:test'),assert=require('node:assert/strict'),h=require('./helpers/operations-ui-harness.cjs');
test('teacher reviews fee and waiver before sending cancellation; retry retains exact payload',async()=>{
 const u=h.createUI('admin',{hash:'#home'});u.requests[0].reply({data:{today:'2026-09-08',slots:[],lessonsToday:[],lessonsWeek:[],pending:[],unpaid:[],students:[],meetings:[],cancelReqs:[{id:'fee-slot',studentId:'test-a',studentName:'【テスト】A',date:'2026-09-08',start:'13:00',min:60,req:{reason:'都合',requestType:'exception'}}]}});await h.flush();u.click('cancelok',{'data-id':'fee-slot','data-sid':'test-a'});
 assert.equal(u.requests.at(-1).body.op,'serviceCancelQuote');u.requests.at(-1).reply({ok:true,signature:'quote-1',history:{month:'2026-09',count:2,items:[{date:'2026-09-01',start:'13:00',subject:'数学',amount:500,reason:'初回',requestReason:'急病'}]},quote:{source:'request',receivedAt:'2026-09-08T01:00:00Z',slot:{date:'2026-09-08',start:'13:00',subject:'英語'},amount:1000}});await h.flush();
 assert.match(u.html(),/キャンセル料：1,000円/);assert.match(u.html(),/今月のキャンセル：2回/);assert.match(u.html(),/500円/);u.input('cf-choice','adjust');u.input('cf-amount','500');u.input('cf-note','急病');u.click('cf-save');const sent=JSON.parse(JSON.stringify(u.requests.at(-1).body));assert.equal(sent.feeChoice,'adjust');assert.equal(sent.feeAmount,'500');assert.equal(sent.note,'急病');assert.equal(sent.op,'resolveCancel');
 u.requests.at(-1).reply({error:'処理中',errorCode:'pending'});await h.flush();assert.match(u.html(),/同じ内容で結果を確認/);u.click('cf-save');assert.deepEqual(JSON.parse(JSON.stringify(u.requests.at(-1).body)),sent);
});

test('teacher can review pending relief from home independent of lesson date',async()=>{const u=h.createUI('admin',{hash:'#home'});u.requests[0].reply({data:{today:'2026-09-08',slots:[],lessonsToday:[],lessonsWeek:[],pending:[],unpaid:[],students:[],meetings:[],cancelReqs:[],cancellations:[{id:'cancel-id',studentId:'test-a',studentName:'【テスト】A',date:'2026-09-01',start:'13:00',subject:'数学',amount:1000,standardAmount:1000,relief:{requestId:'relief-request-01',status:'pending',reason:'急病'}}]}});await h.flush();assert.match(u.html(),/キャンセル料の減額・免除申請/);u.click('relief-open',{'data-id':'cancel-id','data-sid':'test-a'});assert.match(u.html(),/申請理由：急病/);u.input('relief-amount','500');u.input('relief-note','減額します');u.click('relief-save');assert.equal(u.requests.at(-1).body.op,'serviceCancelReliefReview');assert.equal(u.requests.at(-1).body.amount,'500');assert.equal(u.requests.at(-1).body.requestId,'relief-request-01');});
