'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createSchedulingHarness}=require('./helpers/scheduling-harness.cjs');
const request=(patch={})=>({requestId:'meeting-test-001',studentId:'test-a',date:'2026-09-15',start:'12:00',min:30,who:'保護者',deliveryMode:'in_person',note:'相談',...patch});
test('meetings persist separately, retry safely, cancel without affecting lessons',()=>{const h=createSchedulingHarness(),c=h.context();const before=h.rows('slots').length;let r=h.admin('meetingCreate',request());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(h.rows('meetingSchedules').length,1);assert.equal(h.admin('meetingCreate',request()).ok,true);assert.equal(h.rows('meetingSchedules').length,1);assert.ok(h.admin('meetingCreate',request({min:60})).error);assert.equal(h.rows('slots').length,before);assert.equal(c.meetingRows_('test-b').length,0);const m=h.rows('meetingSchedules')[0];assert.ok(h.admin('meetingCancel',{meetingId:m.id,studentId:'test-b'}).error);assert.equal(h.admin('meetingCancel',{meetingId:m.id,studentId:'test-a'}).ok,true);assert.equal(h.context().meetingRows_().length,0);assert.equal(h.admin('meetingCancel',{meetingId:m.id,studentId:'test-a'}).ok,true);});
test('meeting and lesson overlaps rejected in both directions; adjacency allowed',()=>{const h=createSchedulingHarness(),c=h.context();h.seedSlot({date:'2026-09-15',start:'12:00',min:30,status:'booked'});assert.ok(h.admin('meetingCreate',request()).error);assert.equal(h.admin('meetingCreate',request({start:'12:30'})).ok,true);assert.ok(c.schedulingCapacityError_({date:'2026-09-15',start:'12:45',min:30,subject:'英語',deliveryMode:'in_person',studentId:'test-b'},[],''));assert.equal(c.schedulingCapacityError_({date:'2026-09-15',start:'13:00',min:30,subject:'英語',deliveryMode:'in_person',studentId:'test-b'},[],''),null);});
test('invalid inputs and unauthorized access do not create meetings',()=>{const h=createSchedulingHarness();for(const patch of [{date:'2026-02-30'},{start:'25:00'},{min:0},{min:200},{who:'other'},{deliveryMode:'x'},{studentId:'missing'}])assert.ok(h.admin('meetingCreate',request(patch)).error,JSON.stringify(patch));const r=h.requestWith({action:'admin',op:'meetingCreate',token:'invalid',...request()});assert.ok(r.error);assert.equal(h.rows('meetingSchedules').length,0);});
test('online uses existing deterministic Calendar/Meet request with no invites',()=>{const h=createSchedulingHarness(),c=h.context();let body; c.isTestStudent_=()=>false;c.getConfig_=()=> 'on';c.Calendar={Events:{get(){throw Error('404');},insert(b){body=b;return {...b,hangoutLink:'https://meet.google.com/test'};}}};c.memoClear_();assert.equal(c.meetingCreate_(request({deliveryMode:'online'})).ok,true);assert.ok(body.conferenceData);assert.match(body.summary,/ミーティング/);assert.equal(body.attendees,undefined);assert.equal(h.rows('meetingSchedules')[0].meetUrl,'https://meet.google.com/test');});

test('D1 stores meetings and writes back Meet without altering lessons',async()=>{
 const {createParity}=require('./helpers/parity-harness.cjs');const h=createSchedulingHarness(),p=await createParity(h),{runWrite,deliverEffects}=await import('../cf/worker/write.mjs');const {TEACHER_TOKEN}=require('./gas-harness.cjs');
 const r=await runWrite({action:'admin',token:TEACHER_TOKEN,op:'meetingCreate',...request()},p.env,{now:new Date('2026-09-08T00:00:00Z')});assert.equal(r.result.ok,true,JSON.stringify(r.result));
 assert.equal((await p.d1.prepare('select * from meetingSchedules').all()).results.length,1);
 await p.d1.prepare("update meetingSchedules set eventId='st-test@google.com', deliveryMode='online'").run();
 const oldFetch=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({writebacks:[{marker:'st-test',eventId:'st-test@google.com',meetUrl:'https://meet.google.com/test'}]})});
 try{await deliverEffects({...p.env,GAS_URL:'https://example.test',SYNC_KEY:'test'},[{kind:'calendarMeet'}],[]);assert.equal((await p.d1.prepare('select meetUrl from meetingSchedules').first()).meetUrl,'https://meet.google.com/test');}finally{global.fetch=oldFetch;}
});

test('late Calendar creation for cancelled meeting is deleted and never revived',async()=>{const {createD1}=require('./helpers/d1-harness.cjs'),db=createD1(),{deliverEffects}=await import('../cf/worker/write.mjs');await db.prepare("insert into meetingSchedules(id,status,eventId) values ('cancelled','cancelled','late@google.com')").run();const requests=[],old=global.fetch;global.fetch=async(url,args)=>{const body=JSON.parse(args.body);requests.push(body);return {ok:true,json:async()=>({writebacks:body.items[0].kind==='calendarDelete'?[]:[{marker:'late',eventId:'late@google.com',meetUrl:'https://meet.google.com/test'}]})};};try{await deliverEffects({DB:db,GAS_URL:'https://example.test',SYNC_KEY:'test'},[{kind:'calendarCreate'}],[]);assert.equal(requests[1].items[0].kind,'calendarDelete');assert.equal((await db.prepare("select meetUrl from meetingSchedules where id='cancelled'").first()).meetUrl,'');}finally{global.fetch=old;}});
