const assert=require('node:assert/strict'),{test}=require('node:test'),h=require('./helpers/operations-ui-harness.cjs');
test('selected lesson cancellation asks for reason before sending',async()=>{const u=await h.studentReady(h.state([h.slot('booked',{st:'mine'})]));u.click('calday',{'data-date':'2026-09-10'});assert.match(u.html(),/>キャンセル<\/button>/);u.click('askcancel',{'data-id':'booked'});assert.ok(u.el('f-creason'));assert.match(u.html(),/キャンセル申請/);assert.equal(u.requests.length,1);u.click('closebar');assert.equal(u.requests.length,1);});

test('cancellation distinguishes previous-day 23:00 boundary and shows submitted state',async()=>{for(const [now,late] of [['2026-09-09T22:59:00+09:00',false],['2026-09-09T23:00:00+09:00',false],['2026-09-09T23:01:00+09:00',true]]){const s=h.state([h.slot('booked',{st:'mine'})]);const u=h.createUI('student',{now});u.requests[0].reply(s);await h.flush();u.click('calday',{'data-date':'2026-09-10'});u.click('askcancel',{'data-id':'booked'});assert.match(u.html(),/キャンセル料は、申請理由を確認したうえで確定/);assert.doesNotMatch(u.html(),/先生が確認してから取消|原則取消不可のため/);u.input('f-creason','体調不良');u.click('docancel');assert.equal(u.requests.at(-1).body.action,'cancelReq');s.slots[0].req={reason:'体調不良'};u.requests.at(-1).reply({state:s});await h.flush();assert.match(u.html(),/キャンセル申請中/);assert.match(u.html(),/依頼を取り下げる/);}});

test('cancelled lessons remain in selected day without cancellation actions',async()=>{const s=h.state([]);s.cancellations=[{id:'cancelled',date:'2026-09-10',start:'13:00',min:60,subject:'数学',st:'cancelled'}];const u=h.createUI('student');u.requests[0].reply(s);await h.flush();u.click('calday',{'data-date':'2026-09-10'});assert.match(u.html(),/13:00〜14:00/);assert.match(u.html(),/data-action="cancel-review"[^>]*>キャンセル済み/);assert.doesNotMatch(u.html(),/data-action="askcancel"/);});

test('cancel alert opens review and acknowledgement removes alert',async()=>{const s=h.state([]);s.cancellations=[{id:'cancelled',date:'2026-09-10',start:'13:00',min:60,subject:'数学',st:'cancelled',amount:500,standardAmount:1000,receivedAt:'2026-09-09T14:30:00Z',source:'external',confirmed:false}];const u=h.createUI('student');u.requests[0].reply(s);await h.flush();u.click('calday',{'data-date':'2026-09-10'});u.click('cancel-review',{'data-id':'cancelled'});assert.match(u.html(),/キャンセル内容の確認/);assert.match(u.html(),/scope="row"/);assert.match(u.html(),/減額（500円）/);assert.match(u.html(),/2026\/09\/09 23:30/);assert.match(u.html(),/適用中のキャンセル料/);u.click('cancel-confirm');assert.equal(u.requests.at(-1).body.reason,undefined);assert.equal(u.requests.at(-1).body.action,'cancelAcknowledge');s.cancellations[0].confirmed=true;u.requests.at(-1).reply({ok:true,state:s});await h.flush();assert.doesNotMatch(u.html(),/aria-label="キャンセル内容を確認"/);assert.match(u.html(),/data-action="cancel-review"/);});

test('acknowledged cancellation still allows a separate relief request',async()=>{const s=h.state([]);s.cancellations=[{id:'cancelled',date:'2026-09-10',start:'13:00',min:60,subject:'数学',st:'cancelled',amount:1000,standardAmount:1000,source:'request',confirmed:true}];const u=h.createUI('student');u.requests[0].reply(s);await h.flush();u.click('calday',{'data-date':'2026-09-10'});u.click('cancel-review',{'data-id':'cancelled'});assert.doesNotMatch(u.html(),/data-action="cancel-confirm"/);u.input('cancel-circumstances','急病でした');u.click('cancel-relief-send');const body=u.requests.at(-1).body;assert.equal(body.action,'cancelReliefRequest');assert.equal(body.reason,'急病でした');assert.ok(body.requestId);s.cancellations[0].relief={status:'pending',reason:'急病でした'};u.requests.at(-1).reply({ok:true,state:s});await h.flush();u.click('cancel-review',{'data-id':'cancelled'});assert.match(u.html(),/請求確定を保留/);assert.doesNotMatch(u.html(),/data-action="cancel-relief-send"/);});
