'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createFamilyHarness}=require('./helpers/family-harness.cjs');
function fixture(){const h=createFamilyHarness(),c=h.context();c.ensureFamilySchema_();const a={id:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',label:'【テスト】家族',status:'active',email:'parent@example.invalid',verifiedAt:'2026-09-01',passHash:'fixture'};c.familySave_(a);c.familySetChildren_(a,['test-a']);return {h,ftoken:c.familyIssueSession_(a).ftoken};}
function save(f,permission,allowed=false,expectedRevision=0){return f.h.request({action:'familyPermissionsSave',ftoken:f.ftoken,studentId:'test-a',permission,allowed,expectedRevision});}
test('permissions default to allowed, require parent membership, and use revision conflict checks',()=>{const f=fixture(),{h,ftoken}=f;assert.ok(Object.values(h.context().studentPermissions_('test-a')).every(Boolean));assert.ok(h.request({action:'familyPermissionsSave',studentId:'test-a',permission:'booking',allowed:false,expectedRevision:0}).error);assert.ok(h.request({action:'familyPermissionsSave',ftoken,studentId:'test-b',permission:'booking',allowed:false,expectedRevision:0}).error);assert.equal(save(f,'booking').ok,true);assert.equal(save(f,'events').errorCode,'conflict');assert.equal(save(f,'events',false,1).ok,true);assert.ok(save(f,'unknown',false,2).error);const c=h.request({action:'familyHome',ftoken}).children[0];assert.equal(c.permissions.booking,false);assert.equal(c.permissions.events,false);assert.equal(c.permissions.request,true);assert.equal(c.permissionsRevision,2);assert.equal(h.context().studentPermissions_('test-b').booking,true);});
test('all six restrictions reject student writes, including spoofed parent proxy',()=>{const f=fixture(),{h}=f,k=h.studentRow().code;['booking','reschedule','request','availability','events','email'].forEach((p,i)=>assert.equal(save(f,p,false,i).ok,true));for(const b of [{action:'accept'},{action:'acceptMany'},{action:'decline'},{action:'cancelReq'},{action:'wish',kind:'want'},{action:'wishMany',kind:'want'},{action:'wish',kind:'available'},{action:'block'},{action:'blockSet'},{action:'unblock'},{action:'eventAdd'},{action:'eventAddMany'},{action:'eventDel'},{action:'studentEmailRequest'},{action:'studentEmailResend'},{action:'studentEmailRemove'}]){assert.equal(h.request({...b,k,familyProxy:true}).errorCode,'studentPermissionDenied',b.action);}assert.equal(h.context().studentState_(k).permissions.booking,false);});
test('parent proxy retains authority and event blocking needs availability permission',()=>{const f=fixture(),{h,ftoken}=f,k=h.studentRow().code;assert.equal(save(f,'availability').ok,true);assert.equal(h.request({action:'eventAdd',k,alsoBlock:true}).permission,'availability');assert.equal(h.request({action:'block',k}).errorCode,'studentPermissionDenied');assert.notEqual(h.request({action:'block',ftoken,studentId:'test-a'}).errorCode,'studentPermissionDenied');});

test('legacy cancellation and wish deletion cannot bypass the operation permissions',()=>{const f=fixture(),{h}=f,k=h.studentRow().code;save(f,'reschedule');assert.equal(h.request({action:'learningService',op:'cancelRequest',k}).errorCode,'studentPermissionDenied');save(f,'request',false,1);const c=h.context();c.ss_().getSheetByName('wishes').appendRow(['permission-wish','test-a','2026-09-28','17:00','18:00','','','want']);c.memoClear_();assert.equal(h.request({action:'unwish',k,wishId:'permission-wish',kind:'ok'}).permission,'request');});
const {studentReady,state,flush}=require('./helpers/operations-ui-harness.cjs');
test('student controls reflect restrictions without blocking reading',async()=>{const ui=await studentReady({...state(),permissions:{booking:false,reschedule:false,request:false,availability:false,events:false,email:false}});assert.match(ui.html(),/一部の操作は保護者のみ/);assert.match(ui.html(),/data-action="askaccept"[^>]*disabled/);assert.match(ui.html(),/data-action="askdecline"[^>]*disabled/);ui.navigate('#student-email');assert.match(ui.html(),/id="se-email"[^>]*disabled/);assert.match(ui.html(),/type="submit"[^>]*disabled/);assert.doesNotMatch(ui.html(),/data-action="se-pref"[^>]*disabled/);});

test('student home combines plan and progress with a read-only detail dialog',async()=>{const ui=await studentReady({...state(),planLines:[{id:'test-plan',status:'proposed',subject:'数学',kind:'通常',count:6,lessonMin:90,startDate:'2026-09-01',endDate:'2026-09-30',comment:'計画の説明'}]});assert.match(ui.html(),/授業計画・実施状況/);assert.doesNotMatch(ui.html(),/data-fold="plan"|data-fold="progress"/);assert.match(ui.html(),/data-action="student-planopen"/);const before=ui.requests.length;ui.click('student-planopen',{'data-line':'test-plan'});assert.match(ui.html(),/id="student-plan-dialog"/);assert.match(ui.html(),/計画の説明/);assert.match(ui.html(),/保護者ページから/);assert.doesNotMatch(ui.html(),/data-action="fa-planok"|data-action="fa-decide"/);assert.equal(ui.requests.length,before);ui.click('student-planclose');assert.doesNotMatch(ui.html(),/id="student-plan-dialog"/);});
