const test=require('node:test'),assert=require('node:assert/strict');
const {studentReady,adminReady,state,slot,card,flush,createUI}=require('./helpers/operations-ui-harness.cjs');
const receipt={requestId:'synthetic-receipt',revision:'revision-1',status:'pending',snapshot:{id:'slot-a',date:'2026-09-10',start:'17:00',min:30,subject:'英語',deliveryMode:'in_person'}};
const lesson=()=>slot('slot-a',{st:'mine',teacherBooking:receipt});
test('student reviews a booked lesson and sends correction without cancellation',async()=>{const ui=await studentReady(state([lesson()]));ui.click('calday',{'data-date':'2026-09-10'});ui.click('booking-review');assert.match(ui.html(),/内容に間違いはありませんか/);ui.click('booking-correct');assert.equal(ui.requests.length,1);ui.input('booking-review-note','開始時刻の確認をお願いします');ui.click('booking-correct');assert.equal(ui.requests.at(-1).body.action,'teacherBookingRespond');assert.equal(ui.requests.at(-1).body.response,'correction');assert.equal(ui.requests.at(-1).body.slotId,'slot-a');});
test('student can acknowledge and preview cannot submit',async()=>{const ui=await studentReady(state([lesson()]));ui.click('calday',{'data-date':'2026-09-10'});ui.click('booking-review');ui.click('booking-confirm');assert.equal(ui.requests.at(-1).body.response,'confirmed');const preview=createUI('student',{search:'?preview=student:test-a'});preview.requests[0].reply(state([lesson()]));await flush();preview.click('calday',{'data-date':'2026-09-10'});preview.click('booking-review');const count=preview.requests.length;preview.click('booking-confirm');assert.equal(preview.requests.length,count);});
test('teacher opens offered lesson and retains request ID on retry',async()=>{const ui=await adminReady(card({lessons:[{...lesson(),status:'offered',teacherBooking:null}]}));ui.click('calday',{'data-date':'2026-09-10'});ui.click('teacher-book-open');ui.click('teacher-book-send');let req=ui.requests.at(-1);assert.equal(req.body.op,'teacherBook');const id=req.body.requestId;req.fail();await flush();ui.click('teacher-book-send');assert.equal(ui.requests.at(-1).body.requestId,id);});
test('family response targets the chosen sibling',async()=>{const ui=createUI('student',{hash:'#family/home',session:new Map([['sw_ft_v1','synthetic-family-session']])});let answered=0;for(let i=0;i<10;i++){const pending=ui.requests.slice(answered);if(!pending.length)break;answered=ui.requests.length;for(const r of pending){if(r.body.action==='familyHome')r.reply({ok:true,family:{id:'test-family'},children:[{studentId:'test-a',name:'【テスト】兄'},{studentId:'test-b',name:'【テスト】弟'}]});else if(r.body.action==='familyStudentState')r.reply(state([lesson()]));else if(r.body.action==='familyNotices')r.reply({ok:true,notices:[]});else r.reply({ok:true,data:{month:'2026-09',planLines:[],payments:[],thisMonth:{}}});}await flush();}ui.click('family-calday',{'data-date':'2026-09-10'});ui.click('booking-review',{'data-home-child':'test-b'});ui.click('booking-confirm');assert.equal(ui.requests.at(-1).body.studentId,'test-b');assert.equal(ui.requests.at(-1).body.ftoken,'synthetic-family-session');assert.equal(ui.requests.at(-1).body.action,'teacherBookingRespond');});


test('change circumstances are shown as an escaped table in student review',async()=>{const s=lesson();s.teacherBooking={...receipt,changes:[{before:receipt.snapshot,after:{...receipt.snapshot,start:'18:00'},context:{receivedAt:'2026-09-10T16:00',reason:'遅刻',note:'電話 <script>bad</script>'}}]};const ui=await studentReady(state([s]));ui.click('calday',{'data-date':'2026-09-10'});ui.click('booking-review');assert.match(ui.html(),/連絡受付日時/);assert.match(ui.html(),/2026-09-10 16:00/);assert.match(ui.html(),/遅刻/);assert.match(ui.html(),/&lt;script&gt;/);assert.match(ui.html(),/<table/);});

test('completed lesson details show tables and allow context-only editing',async()=>{const s={...lesson(),status:'booked',done:true,teacherBooking:{...receipt,changes:[{id:'change-a',revision:'rev-a',before:receipt.snapshot,after:{...receipt.snapshot,start:'18:00'},context:null}]}};const ui=await adminReady(card({lessons:[s]}));ui.click('calday',{'data-date':'2026-09-10'});ui.click('slotedit');assert.match(ui.html(),/授業の詳細/);assert.match(ui.html(),/実施済み/);assert.match(ui.html(),/日時変更の経緯/);ui.click('se-context');ui.input('context-reason','遅刻');ui.input('context-note','電話連絡');ui.click('se-context-save');assert.equal(ui.requests.at(-1).body.op,'serviceChangeContextSave');assert.equal(ui.requests.at(-1).body.changeNote,'電話連絡');});

test('receipt year inference handles year boundary, invalid dates and existing year',()=>{const source=require('fs').readFileSync(require('path').join(__dirname,'../kanri/index.html'),'utf8');const fn=source.slice(source.indexOf('function contextDateValue('),source.indexOf('function saveChangeContext('));const convert=require('vm').runInNewContext('('+fn.trim()+')');const now=Date.parse('2027-01-02T12:00:00+09:00');assert.equal(convert('12','31','16:00','',now),'2026-12-31T16:00');assert.equal(convert('1','1','16:00','',now),'2027-01-01T16:00');assert.equal(convert('12','31','16:00','2025-12-31T15:00',now),'2025-12-31T16:00');assert.throws(()=>convert('2','30','16:00','',now));assert.throws(()=>convert('1','3','16:00','',now));assert.throws(()=>convert('1','','16:00','',now));assert.equal(convert('','','','',now),'');});
