const test=require('node:test'),assert=require('node:assert/strict');
const {createSchedulingHarness,failWriteOnce}=require('./helpers/scheduling-harness.cjs');
function setup(){const h=createSchedulingHarness();h.approve();const slot=h.seedSlot();const req={studentId:'test-a',slotId:slot.id,requestId:'synthetic-teacher-1',expectedSnapshot:h.snapshot(slot.id)};return {h,slot,req};}
function reply(h,slot,response='confirmed',extra={}){const c=h.context(),r=c.teacherBookingInfo_(h.rows('slots').find(x=>x.id===slot.id));return h.request({action:'teacherBookingRespond',k:'synthetic-link-a',slotId:slot.id,requestId:r.requestId,expectedSnapshot:r.snapshot,expectedRevision:r.revision,response,note:response==='correction'?'時間が違います':'',...extra});}
test('teacher books once and the student confirms separately',()=>{const {h,slot,req}=setup();assert.equal(h.admin('teacherBook',req).ok,true);assert.equal(h.admin('teacherBook',req).ok,true);assert.equal(h.rows('acceptWrites').length,1);assert.equal(h.context().teacherBookingInfo_(h.rows('slots')[0]).status,'pending');assert.equal(reply(h,slot).ok,true);assert.equal(reply(h,slot).ok,true);assert.equal(h.context().teacherBookingInfo_(h.rows('slots')[0]).status,'confirmed');assert.equal(h.rows('slots')[0].status,'booked');});
test('correction is visible to the teacher but does not cancel the booking',()=>{const {h,slot,req}=setup();h.admin('teacherBook',req);assert.equal(reply(h,slot,'correction').ok,true);const info=h.admin('state').admin.slots[0].teacherBooking;assert.equal(info.status,'correction');assert.equal(info.note,'時間が違います');assert.equal(h.rows('slots')[0].status,'booked');assert.ok(reply(h,slot).error);});
test('authentication, student ownership and permissions are enforced',()=>{const {h,slot,req}=setup();assert.ok(h.request({action:'admin',op:'teacherBook',...req}).error);assert.ok(h.admin('teacherBook',{...req,studentId:'test-b'}).error);h.admin('teacherBook',req);assert.ok(reply(h,slot,'confirmed',{k:'synthetic-link-b'}).error);const c=h.context();c.ensureSheet_(h.spreadsheet,'studentPermissions',c.STUDENT_PERMISSION_COLS_).appendRow(['test-a','0','0','1','1','1','1','1']);assert.equal(reply(h,slot).errorCode,'studentPermissionDenied');assert.equal(reply(h,slot,'correction',{familyProxy:true}).errorCode,'studentPermissionDenied');assert.ok(h.acceptMany([slot.id],'teacher-synthetic-teacher-1').error);});
test('stale snapshots and conflicting answers are rejected',()=>{const {h,slot,req}=setup();assert.ok(h.admin('teacherBook',{...req,expectedSnapshot:{...req.expectedSnapshot,start:'18:00'}}).error);h.admin('teacherBook',req);const info=h.context().teacherBookingInfo_(h.rows('slots')[0]);h.setRow('slots','id',slot.id,{start:'17:00'});assert.ok(reply(h,slot,'confirmed',{expectedSnapshot:info.snapshot}).error);assert.equal(reply(h,slot).ok,true);h.setRow('slots','id',slot.id,{start:'18:00'});assert.equal(h.admin('state').admin.slots[0].teacherBooking.status,'pending');});
test('capacity checks remain active',()=>{const {h,slot,req}=setup();h.seedSlot({id:'conflicting',status:'booked',studentId:'test-a'});assert.ok(h.admin('teacherBook',req).error);assert.equal(h.rows('teacherBookings').length,0);});
test('lost confirmation receipt retries with the same request',()=>{const {h,slot,req}=setup();failWriteOnce(h.spreadsheet.getSheetByName('acceptWrites'),()=>true,true);assert.ok(h.admin('teacherBook',req).error);assert.equal(h.admin('teacherBook',req).ok,true);assert.equal(h.rows('teacherBookings').length,1);assert.equal(h.rows('acceptWrites').length,1);});
test('D1 saves teacher booking and authenticated parent acknowledgement',async()=>{const {h,slot,req}=setup(),c=h.context();c.ensureFamilySchema_();const family={id:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',label:'【テスト】家族',status:'active',email:'parent@example.invalid',verifiedAt:'2026-09-01',passHash:'fixture'};c.familySave_(family);c.familySetChildren_(family,['test-a']);const ftoken=c.familyIssueSession_(family).ftoken;const {createParity}=require('./helpers/parity-harness.cjs'),p=await createParity(h),{runWrite}=await import('../cf/worker/write.mjs');const booked=await runWrite(h.teacherRequest('teacherBook',req),p.env,{now:h.now()});assert.equal(booked.result.ok,true,JSON.stringify(booked.result));const s=await p.worker({action:'familyStudentState',ftoken,studentId:'test-a'}),info=s.slots.find(x=>x.id===slot.id).teacherBooking;assert.equal(info.status,'pending');const body={action:'teacherBookingRespond',ftoken,studentId:'test-a',slotId:slot.id,requestId:info.requestId,expectedSnapshot:info.snapshot,expectedRevision:info.revision,response:'confirmed'};const denied=await runWrite({...body,studentId:'test-b'},p.env,{now:h.now()});assert.ok(denied.result.error);const result=await runWrite(body,p.env,{now:h.now()});assert.equal(result.result.ok,true,JSON.stringify(result.result));const read=await p.worker({action:'familyStudentState',ftoken,studentId:'test-a'});assert.equal(read.slots.find(x=>x.id===slot.id).teacherBooking.respondedBy,'parent');assert.equal(read.slots.find(x=>x.id===slot.id).teacherBooking.status,'confirmed');});

test('teacher changes a booked time and requests a fresh acknowledgement with original time',()=>{const {h,slot,req}=setup();h.admin('teacherBook',req);reply(h,slot);const before=h.snapshot(slot.id),edit={studentId:'test-a',slotId:slot.id,requestId:'edit-time-test-1',expectedSnapshot:before,date:before.date,start:'18:00',min:60,subject:before.subject,deliveryMode:before.deliveryMode,kind:'通常'};const r=h.admin('editBooked',edit);assert.equal(r.ok,true,JSON.stringify(r));assert.equal(h.admin('editBooked',edit).ok,true);const info=h.context().teacherBookingInfo_(h.rows('slots')[0]);assert.equal(info.status,'pending');assert.equal(info.previous.start,before.start);assert.equal(info.snapshot.start,'18:00');assert.equal(reply(h,slot).ok,true);assert.equal(h.admin('editBooked',edit).ok,true);assert.equal(h.context().teacherBookingInfo_(h.rows('slots')[0]).status,'confirmed');assert.equal(h.rows('offerEdits').length,1);});
test('booked date edit rejects stale and overlapping changes',()=>{const {h,slot,req}=setup();h.admin('teacherBook',req);const before=h.snapshot(slot.id),edit={studentId:'test-a',slotId:slot.id,requestId:'edit-time-test-2',expectedSnapshot:before,date:before.date,start:'18:00',min:60,subject:before.subject,deliveryMode:before.deliveryMode};h.seedSlot({id:'other',studentId:'test-a',status:'booked',start:'18:00',min:60});assert.ok(h.admin('editBooked',edit).error);assert.equal(h.rows('slots')[0].start,before.start);assert.ok(h.admin('editBooked',{...edit,expectedSnapshot:{...before,start:'20:00'}}).error);});
